### ISSUE TITLE
X-plane free draw for XARM

### ISSUE THREAD

**Issue by craigvear** [DigiScore/jess_plus#18]
The new XARM allows for a great movement. Modify 'continuous movement' so that there is an extended range of movement possibilities in the X-plane.

An extended set of extents has been included in config.py to deal with this.

Watch out for:
- reduced TCP boundary and safety position checker - this may need over-riding for continuous.
- ensure full dc-strings and appropriate comments are included
- use var definitions in def func(self) init 
- DO NOT CANGE composer.py this task needs to modify drawXArm.py only

**Comment by HanBnrd** [comment]
Hi @craigvear, can this be closed?
