### ISSUE TITLE
`go_position_ready` goes to drawing position

### ISSUE THREAD

**Issue by HanBnrd** [DigiScore/jess_plus#26]
**Steps to reproduce:**
```python
from modules.drawXarm import DrawXarm
import config

port = config.xarm1_port
drawbot = DrawXarm(port)

drawbot.go_position_ready()
```

**Expected result:**
Goes to ready position

**Actual result:**
Goes to draw position

task: define all ready and draw positions for xarm

**Comment by craigvear** [comment]
These have yet to be defined. Willl amend this ticket

**Comment by HanBnrd** [comment]
Hi Craig, the positions are already defined, I think it just requires to fix the methods. I will make a PR for it.
