### ISSUE TITLE
Speed Exceeds Limit with `go_random_jump`

### ISSUE THREAD

**Issue by HanBnrd** [DigiScore/jess_plus#28]
**Steps to reproduce:**
```python
from modules.drawXarm import DrawXarm
import config

port = config.xarm1_port
drawbot = DrawXarm(port)

drawbot.go_position_draw()
drawbot.go_random_jump()
drawbot.go_position_draw()
drawbot.go_random_jump()
```

**Expected result:**
Does a random jump

**Actual result:**
Controller Error: Speed Exceeds Limit

**Comment by craigvear** [comment]
What was the speed param? Does it do this error every time? Regardless of speed variable?

**Comment by HanBnrd** [comment]
Speed was 100. But I think this issue is probably related to #27 actually.
